Repository COS301-SE-2022/Chopper-Charlie, pull requests merged in 2022-05, with the labels that each got.

#15 Frontend develop
  package-lock.json
  package.json
  reactapp/.gitignore
  reactapp/README.md
  reactapp/package-lock.json
  reactapp/package.json
  reactapp/public/favicon.ico
  reactapp/public/index.html
  reactapp/public/manifest.json
  reactapp/public/robots.txt
  reactapp/src/App.css
  reactapp/src/App.js
  reactapp/src/App.test.js
  reactapp/src/index.css
  reactapp/src/index.js
  reactapp/src/reportWebVitals.js
  reactapp/src/setupTests.js
Labels: scope:frontend

#16 Backend develop
  AzeurBlobRetrieve/azeurblobretrieve.py
  AzeurBlobUpload/azeurblobupload.py
Labels: priority:medium

#17 merge into master
  AzeurBlobRetrieve/azeurblobretrieve.py
  AzeurBlobUpload/azeurblobupload.py
  package-lock.json
  package.json
  reactapp/.gitignore
  reactapp/README.md
  reactapp/package-lock.json
  reactapp/package.json
  reactapp/public/favicon.ico
  reactapp/public/index.html
  reactapp/public/manifest.json
  reactapp/public/robots.txt
  reactapp/src/App.css
  reactapp/src/App.js
  reactapp/src/App.test.js
  reactapp/src/index.css
  reactapp/src/index.js
  reactapp/src/reportWebVitals.js
  reactapp/src/setupTests.js
Labels: priority:medium, scope:backend, status:ready, type:update, role:developer, role:teamlead, scope:frontend

#19 Develop
  AzureBlobRetrieve/azureblobretrieve.py
  AzureBlobUpload/azureblobupload.py
  ImageAI/.gitattributes
  ImageAI/__pycache__/DetectCar.cpython-39.pyc
  ImageAI/__pycache__/detection_car.cpython-39.pyc
  ImageAI/__pycache__/vehicle_detector.cpython-39.pyc
  ImageAI/carss.jpg
  ImageAI/vehicle_counting.py
  ImageAI/vehicle_detector.py
  ImageAI/yolov4.cfg
  VideoAI/AI.py
  VideoAI/cars.xml
Labels: priority:high, scope:ui, scope:ai, scope:backend, scope:db, scope:frontend
